FROM node:20-alpine AS build
WORKDIR /app
ARG VITE_API_URL
ARG VITE_SOCKET_URL
ARG VITE_CLIENT_PUBLIC_URL
ARG VITE_APP_NAME
ARG VITE_ADMIN_PUBLIC_BASE_URL
ARG VITE_ADMIN_TEST_PUBLIC_BASE_URL
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SOCKET_URL=$VITE_SOCKET_URL
ENV VITE_CLIENT_PUBLIC_URL=$VITE_CLIENT_PUBLIC_URL
ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_ADMIN_PUBLIC_BASE_URL=$VITE_ADMIN_PUBLIC_BASE_URL
ENV VITE_ADMIN_TEST_PUBLIC_BASE_URL=$VITE_ADMIN_TEST_PUBLIC_BASE_URL
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
